<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Axiom.State" Version="0.5.0" />
		<PackageReference Include="TestFramework.Core" Version="0.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestFramework.DebugUI.Docking\TestFramework.DebugUI.Docking.csproj" />
	</ItemGroup>

</Project>
