<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		<RootNamespace>TestFramework.DebugUI</RootNamespace>

		<!-- Declares per-monitor DPI awareness. See app.manifest for why. -->
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Shaders\HLSL\BlurShader.ps" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Axiom.State" Version="0.5.0" />
		<PackageReference Include="Axiom.Wpf" Version="0.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestFramework.DebugUI.Docking\TestFramework.DebugUI.Docking.csproj" />
		<ProjectReference Include="..\TestFramework.DebugUI.Layout\TestFramework.DebugUI.Layout.csproj" />
		<ProjectReference Include="..\TestFramework.DebugUI.State\TestFramework.DebugUI.State.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Shaders\HLSL\BlurShader.ps">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
