<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Shaders\HLSL\BlurShader.ps" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>TestFramework.ConsumerScenarios.DebugUI.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestFramework.DebugUI.Data\TestFramework.DebugUI.Data.csproj" />
		<ProjectReference Include="..\TestFramework.DebugUI.PipeAdapter\TestFramework.DebugUI.PipeAdapter.csproj" />
		<ProjectReference Include="..\WpfStateService\WpfStateService.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Shaders\HLSL\BlurShader.ps">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
