<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestFramework.DebugUI.State\TestFramework.DebugUI.State.csproj" />
	</ItemGroup>

</Project>
